### ISSUE TITLE
New enclosure rev 1 design problem.

### ISSUE THREAD

**Issue by joonasstenvall** [keebio/sinc-case#2]
The rev1 pcb connectors do not fit the current enclosure design.

## Expected Behavior
The pcb should just pop in. The tssr connector is too big for current hole. The USB-C might be problematic too.

## Current Behavior
Pcb does not go in fully when assembling. Tried to install normally but I could not get it to fix.

## Possible Solution
Enlarge the connector holes. I fixed this in a minute by plunging a soldering iron throw the holes in order to enlarge them. Would not recommend.

## Context 
Was not ideal for my build. Altough I wish I did not have to enlarge the holes with an soldering iron.

**Comment by nooges** [comment]
Can you take a picture and post it here? I did do a test print of https://github.com/keebio/sinc-case/blob/master/enclosed-case/Mid%20Layer%20-%20Rev%201%20Left%20Macro.stl and https://github.com/keebio/sinc-case/blob/master/enclosed-case/Mid%20Layer%20-%20Rev%201%20Right.stl, and they fit fine with my build.

**Comment by joonasstenvall** [comment]
![1](https://user-images.githubusercontent.com/78197617/129416500-d85359d2-d518-46c3-b267-7c68b318b932.jpeg)
![2](https://user-images.githubusercontent.com/78197617/129416505-f2998956-3d36-445a-8218-75db14487955.jpeg)

Sorry for the bad pictures. I have my left half fully assembled and I did not want to take it apart for a couple of pictures.
Maybe the tolerances are so tight that my printer could not print it right? But when inserting the pcb for the first time, I did get the pcb in but there was noticable collision between trrs port and the housing.

**Comment by nooges** [comment]
The plate edge should not be flush with the case edge, as it should be 4mm from the edge (top shell will cover the gap). It should look like this in the end:

![image](https://user-images.githubusercontent.com/204212/129417981-8fccb64c-40d1-4250-b06e-1d408f67c6da.png)

**Comment by joonasstenvall** [comment]
Oh my, I done goofed up. Your build looks great btw!

**Comment by LGMagnaCarter** [comment]
Hi, I am getting a similar issue. 

From looking at it, the trrs port is a square where it passes, and the case is a circle. I guess I just have to make an expansion now?
![16476924514187983160515725122654](https://user-images.githubusercontent.com/68279397/159120882-c9a111f9-fc92-43e6-8f5b-c2bcc180a189.jpg)

**Comment by nooges** [comment]
As mentioned earlier in previous comment, the middle layer edge is not supposed to be flush with the plate edge. It’s 4mm extra on the sides.

**Comment by LGMagnaCarter** [comment]
I understand this, but the extruding PCB that the trrs & usbc is soldered to blocks the screw holes from aligning
![16476973040675617678626627803809](https://user-images.githubusercontent.com/68279397/159123494-816bb813-b7c9-4227-b29c-2c123d979319.jpg)

**Comment by nooges** [comment]
Okay, turns out the test fit I had done here (https://github.com/keebio/sinc-case/issues/2#issuecomment-898718051) was with a prototype version of the PCB that had the ports inset more by about 3.5mm.

I'll be reworking the middle layers and will post up new files.

**Comment by nooges** [comment]
Fixed now with https://github.com/keebio/sinc-case/commit/ac028336c68fa8048dcde10466cd0a61806cf683
These have been printed and tested with the production Rev. 1 PCB.
