### ISSUE TITLE
Clarify requirements for enclosed case.

### ISSUE THREAD

**Issue by Shazib** [keebio/sinc-case#5]
Hi, 

I have recently purchased sinc prebuilt from keeb.io which comes with the FR4 plates and have a couple queries

What are all the items i need if want to print the enclosed case? I think:

- Top Shell - Left Macro with Encodes
- Top Shell - Right with Encoder
- Mid Layer - Rev 2 Left Macro
- Mid Layer - Rev 2 Right

Questions:
1. Do i also need 'switch-plate' and 'Bottom-plate' (or are these part of the pre-built)? 
2. What is the 5mm plate used for?
3. Also, is it possible to get the enclosed case files in STEP format? The place where i am sending the print requires STEP.

Many thanks!

**Comment by nooges** [comment]
I've reorganized the files in the repository now and updated the README to reflect the changes, so hopefully it's clearer now.

To answer your questions:

> What are all the items i need if want to print the enclosed case? ...

The list you've got is correct.

> Do i also need 'switch-plate' and 'Bottom-plate' (or are these part of the pre-built)?

No, these are already part of the build.

> What is the 5mm plate used for?

That was for the acrylic case design.

> Also, is it possible to get the enclosed case files in STEP format? The place where i am sending the print requires STEP.

I don't have STEP files for these at the moment.

**Comment by Shazib** [comment]
Thanks!

Do you have any format that stores the full 3d/curves/equations vs triangles?
